version: 0.2

run-as: root
             
phases:
   pre_build:
      commands:
        - echo "my commit"
        
   build:
      commands:
          - echo "my commit"
          
            
artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
