version: 0.2

run-as: root
env:
  secrets-manager:
    db_url: hitesh-node-mongo:mongo-url	

             
phases:
   pre_build:
      commands:
        - echo "my commit"
        
   build:
      commands:
        - echo "mongo_db_url=${db_url}" >> .env
        - npm install
          
            
artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
